name: CI

on:
  push:
    branches:
      - "**"          # run on any branch (so feature branches get CI)
  pull_request:
    branches:
      - "**"          # run on any PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests
        env:
          OPENAI_API_KEY: "dummy_key_for_testing"   # dummy so OpenAI client init passes
          TWILIO_AUTH_TOKEN: "dummy_token"          # only used if signature validation enabled
        run: |
          export PYTHONPATH="${{ github.workspace }}"
          pytest -q backend/test_twilio.py